### ISSUE TITLE
Package.json engine tag appears to be incorrect

### ISSUE THREAD

**Issue by anotheredward** [ember-learn/guides-app#400]
The current engine tag is:
```JSON
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  },
```
Recommend we change it to  >= 10.* as it's the new LTS and appears to work well.

No version of node lower than 8 will successfully run `npm start`.

node = v8.15.1 appears to work.

When running node 7.10.1, I get another error message:
```
  - stack: /Users/ed/Documents/guides-app/node_modules/algolia-html-extractor/lib/algoliaHtmlExtractor.js:17
      ...options,
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ed/Documents/guides-app/node_modules/algolia-html-extractor/index.js:1:92)
```

When using node 6.17 and attempting to run `ember serve` I get the following error message:
```
  - stack: /Users/ed/Documents/guides-app/node_modules/ember-cli-deploy-prember-algolia/index.js:58
      upload: async function(context) {
                    ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at PackageInfo.getAddonConstructor (/Users/ed/Documents/guides-app/node_modules/ember-cli/lib/models/package-info-cache/package-info.js:380:18)
```

It's fair to assume that anything less than 6 also doesn't work from these error messages.

**Comment by locks** [comment]
Thanks for pointing this out. Could you send a PR to update it?x

**Comment by anotheredward** [comment]
Sure, here you go: https://github.com/ember-learn/guides-app/pull/402

**Comment by mansona** [comment]
Hi folks 👋 I'm so sorry for not noticing this before you did the work @anotheredward but this repo is no longer active 🙈 I just haven't yet gone through everything and archived the repo

All development for the Ember specific templates for Guidemaker should be done over here: https://github.com/ember-learn/guidemaker-ember-template
